baseurl = "https://jefklakscodex.com/"
title = "Jefklaks Codex"
theme = "jefklak-creative-portfolio"
languageCode = "en-us"
publishDir = "docs"
enableEmoji = true
# for .Lastmod to work with .GitInfo: --enableGitInfo https://gohugo.io/variables/git/
enableGitInfo = true
enableRobotsTXT = true
summaryLength = 20

[Author]
  name = "Wouter Groeneveld"
  email = "wouter.groeneveld@gmail.com"

[markup]
  defaultMarkdownHandler = "goldmark"
  
  [markup.goldmark.renderer]
    unsafe= true

[params]  
  description = "Retro game thoughts"
  copyright = "<a href='/no-copyright'>No &copy; reserved - sharing is caring</a>. <br/>An integral part of <a href='https://brainbaking.com/' rel='noopener' target='_blank'>Brain Baking</a>."
  sidebarAbout = [
    "You’re browsing “The Codex”, a dedicated and highly opinionated website about nostalgic games that left a lasting impression on me."
  ]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Browse All Articles"
  url = "articles/"
  home = true

[[params.navlinks]]
  name = "Appendix"
  url = "tags/"

  [[params.navlinks]]
  name = "About the Codex"
  url = "about/"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
