baseurl = "https://jefklakscodex.com/"
title = "Jefklaks Codex"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
disqusShortname = ""
googleAnalytics = "UA-122825031-1"
publishDir = "docs"
enableEmoji = true
# for .Lastmod to work with .GitInfo: --enableGitInfo https://gohugo.io/variables/git/
enableGitInfo = true

[Author]
  name = "Wouter Groeneveld"
  email = "wouter.groeneveld@gmail.com"

[params]
  style = "default"
  description = "Retro game thoughts"
  copyright = "No &copy; reserved - sharing is caring. <a href='https://github.com/wgroeneveld/jefklakscodex' target='_blank'>Hack away!</a><br/>An integral part of <a href='https://brainbaking.com/' target='_blank'>Brain Baking</a>."
  sidebarAbout = [
    "You’re looking at “The Codex”, a dedicated and highly opinionated website about nostalgic games that left a lasting impression on me."
  ]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Articles Index"
  url = "articles/"
  home = true

[[params.navlinks]]
  name = "Appendix"
  url = "tags/"

  [[params.navlinks]]
  name = "About the Codex"
  url = "about/"

