# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Jefklak creative portfolio"
license = "MIT"
licenselink = "https://github.com/kishaningithub/hugo-creative-portfolio-theme/blob/master/LICENSE"
description = "Jefklaks Codex based on Creative Portfolio"
homepage = "https://github.com/wgroeneveld/jefklakscodex"
tags = ["creative", "portfolio", "projects", "minimal", "responsive"]
features = ["bootstrap", "responsive", "google analytics"]
min_version = 0.20

[author]
  name = "wgroeneveld"
  homepage = "https://github.com/wgroeneveld/jefklakscodex"

# If porting an existing theme
[original]
  name = "Creative portfolio"
  homepage = "https://github.com/kishaningithub"
